### ISSUE TITLE
Diet unable to find specific list of dependencies

### ISSUE THREAD

**Issue by tishun** [Codarama/diet-maven-mojo#5]
"Could not get list of dependencies from Maven, reverting to Maven local repository"

This is due to the fact that we are still unable to extract the specific dependencies and revert to minimizing the entire repo, which is slow as hell and bad as Trump.

**Comment by ayld** [comment]
Crap. Doesn't this magically work on some Maven versions?

**Comment by tishun** [comment]
Works, issue was I was using old code
